version: '3'

services:
  app:
    build:
      ./app
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - postgres
    
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "projectdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"  
    volumes:
      - ./projectdb:/var/lib/postgres/data/projectdb
    ports:
      - "5432:5432"
    expose:
      - 5432
  
