version: '3'

services:
  app:
    build:
      ./app
    ports:
      - "5000:5000"
    expose:
      - 5000
    depends_on:
      - postgres
    
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"  
    volumes:
      - ./projectdb:/var/lib/postgres/data
    ports:
      - "5432:5432"
    expose:
      - 5432
  
